### ISSUE TITLE
NexusImageClean image delete -name xxxxxxx/xxxxx -keep 4  doesn't   work 

### ISSUE THREAD

**Issue by xsunnydong** [xmapst/NexusImageClean#1]
"NexusImageClean image delete -name xxxxxxx/xxxxx -keep 4"  doesn't   work .

[root@test1 ~]# ./NexusImageClean image delete  --name platform/base-data-dict-release  -k 3
2021/11/04 15:15:20 You should either specify the tag or how many images you want to keep
But another command is work
[root@test1 ~]# ./NexusImageClean image delete  --name platform/base-data-dict-release -tag v1.2.0 
2021/11/04 15:16:55 platform/base-data-dict-release image v1.2.0 tag deleted

**Comment by xmapst** [comment]
默认不允许保留小于等于三个[code](https://github.com/xmapst/NexusImageClean/blob/f1272f3ba1ed3303c14609abbb4174d335c675ad/actions.go#L142)

**Comment by xmapst** [comment]
> "NexusImageClean image delete -name xxxxxxx/xxxxx -keep 4" doesn't work .
> 
> [root@test1 ~]# ./NexusImageClean image delete --name platform/base-data-dict-release -k 3 2021/11/04 15:15:20 You should either specify the tag or how many images you want to keep But another command is work [root@test1 ~]# ./NexusImageClean image delete --name platform/base-data-dict-release -tag v1.2.0 2021/11/04 15:16:55 platform/base-data-dict-release image v1.2.0 tag deleted

默认不允许保留小于等于三个[code](https://github.com/xmapst/NexusImageClean/blob/f1272f3ba1ed3303c14609abbb4174d335c675ad/actions.go#L142)
