### ISSUE TITLE
Unable to delete images using keep option 

### ISSUE THREAD

**Issue by sk-darch** [xmapst/NexusImageClean#2]
Hi @xmapst ,

I am trying to delete image using keep option and  I am getting following error message. Please have a look.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x847f82]

goroutine 1 [running]:
main.(*WaitGroup).Done(0x0)
	/mnt/f/GoProject/src/NexusImageClean/pool.go:33 +0x22
main.GetImageTagList(0xc0000ba000, 0x0, 0xc000024ae0)
	/mnt/f/GoProject/src/NexusImageClean/actions.go:220 +0x425
main.deleteAction(0xc00027f240, 0x0, 0x0)
	/mnt/f/GoProject/src/NexusImageClean/actions.go:182 +0xc14
github.com/urfave/cli/v2.(*Command).Run(0xc00011dc20, 0xc00027eec0, 0x0, 0x0)
	/mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4ed
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000259040, 0xc00027ed40, 0x0, 0x0)
	/mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:434 +0xa9f
github.com/urfave/cli/v2.(*Command).startApp(0xc00011d7a0, 0xc00027ed40, 0x914902, 0x7ffc0149f6ed)
	/mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x69b
github.com/urfave/cli/v2.(*Command).Run(0xc00011d7a0, 0xc00027ed40, 0x0, 0x0)
	/mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0x98d
github.com/urfave/cli/v2.(*App).RunContext(0xc000258ea0, 0x9b16a0, 0xc00002c088, 0xc000020070, 0x7, 0x7, 0x0, 0x0)
	/mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81f
github.com/urfave/cli/v2.(*App).Run(...)
	/mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
	/mnt/f/GoProject/src/NexusImageClean/main.go:28 +0x1a6
Build step 'Execute shell' marked build as failure

**Comment by xmapst** [comment]
> 

How do you run it, post the execution process

**Comment by iarrived** [comment]
@xmapst 
>$ ./NexusImageClean  image delete  -n ldwb/amd64/ldwb-cms-server -k 4
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x847f82]

goroutine 1 [running]:
main.(*WaitGroup).Done(0x0)
        /mnt/f/GoProject/src/NexusImageClean/pool.go:33 +0x22
main.GetImageTagList(0xc00039c000, 0x0, 0xc0000b6000)
        /mnt/f/GoProject/src/NexusImageClean/actions.go:220 +0x425
main.deleteAction(0xc00028b240, 0x0, 0x0)
        /mnt/f/GoProject/src/NexusImageClean/actions.go:182 +0xc14
github.com/urfave/cli/v2.(*Command).Run(0xc000115d40, 0xc00028aec0, 0x0, 0x0)
        /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4ed
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc00027eea0, 0xc00028ad40, 0x0, 0x0)
        /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:434 +0xa9f
github.com/urfave/cli/v2.(*Command).startApp(0xc0001158c0, 0xc00028ad40, 0x914902, 0x7fff71c65815)
        /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x69b
github.com/urfave/cli/v2.(*Command).Run(0xc0001158c0, 0xc00028ad40, 0x0, 0x0)
        /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0x98d
github.com/urfave/cli/v2.(*App).RunContext(0xc00027ed00, 0x9b16a0, 0xc000024088, 0xc000020070, 0x7, 0x7, 0x0, 0x0)
        /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81f
github.com/urfave/cli/v2.(*App).Run(...)
        /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /mnt/f/GoProject/src/NexusImageClean/main.go:28 +0x1a6

**Comment by xmapst** [comment]
> @xmapst
> 
> ```shell
> >$ ./NexusImageClean  image delete  -n xxxx/amd64/xxxx-cms-server -k 4
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x847f82]
> 
> goroutine 1 [running]:
> main.(*WaitGroup).Done(0x0)
>         /mnt/f/GoProject/src/NexusImageClean/pool.go:33 +0x22
> main.GetImageTagList(0xc00039c000, 0x0, 0xc0000b6000)
>         /mnt/f/GoProject/src/NexusImageClean/actions.go:220 +0x425
> main.deleteAction(0xc00028b240, 0x0, 0x0)
>         /mnt/f/GoProject/src/NexusImageClean/actions.go:182 +0xc14
> github.com/urfave/cli/v2.(*Command).Run(0xc000115d40, 0xc00028aec0, 0x0, 0x0)
>         /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4ed
> github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc00027eea0, 0xc00028ad40, 0x0, 0x0)
>         /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:434 +0xa9f
> github.com/urfave/cli/v2.(*Command).startApp(0xc0001158c0, 0xc00028ad40, 0x914902, 0x7fff71c65815)
>         /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x69b
> github.com/urfave/cli/v2.(*Command).Run(0xc0001158c0, 0xc00028ad40, 0x0, 0x0)
>         /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0x98d
> github.com/urfave/cli/v2.(*App).RunContext(0xc00027ed00, 0x9b16a0, 0xc000024088, 0xc000020070, 0x7, 0x7, 0x0, 0x0)
>         /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81f
> github.com/urfave/cli/v2.(*App).Run(...)
>         /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
> main.main()
>         /mnt/f/GoProject/src/NexusImageClean/main.go:28 +0x1a6
> ```

dowload last release and try [1.0.1-beta](https://github.com/xmapst/NexusImageClean/releases/tag/1.0.1-beta)

**Comment by xmapst** [comment]
> @xmapst
> 
> ```shell
> >$ ./NexusImageClean  image delete  -n xxxx/amd64/xxxx-cms-server -k 4
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x847f82]
> 
> goroutine 1 [running]:
> main.(*WaitGroup).Done(0x0)
>         /mnt/f/GoProject/src/NexusImageClean/pool.go:33 +0x22
> main.GetImageTagList(0xc00039c000, 0x0, 0xc0000b6000)
>         /mnt/f/GoProject/src/NexusImageClean/actions.go:220 +0x425
> main.deleteAction(0xc00028b240, 0x0, 0x0)
>         /mnt/f/GoProject/src/NexusImageClean/actions.go:182 +0xc14
> github.com/urfave/cli/v2.(*Command).Run(0xc000115d40, 0xc00028aec0, 0x0, 0x0)
>         /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x4ed
> github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc00027eea0, 0xc00028ad40, 0x0, 0x0)
>         /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:434 +0xa9f
> github.com/urfave/cli/v2.(*Command).startApp(0xc0001158c0, 0xc00028ad40, 0x914902, 0x7fff71c65815)
>         /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x69b
> github.com/urfave/cli/v2.(*Command).Run(0xc0001158c0, 0xc00028ad40, 0x0, 0x0)
>         /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0x98d
> github.com/urfave/cli/v2.(*App).RunContext(0xc00027ed00, 0x9b16a0, 0xc000024088, 0xc000020070, 0x7, 0x7, 0x0, 0x0)
>         /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0x81f
> github.com/urfave/cli/v2.(*App).Run(...)
>         /mnt/f/GoProject/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
> main.main()
>         /mnt/f/GoProject/src/NexusImageClean/main.go:28 +0x1a6
> ```

@iarrived  dowload last release and try [1.0.1-beta](https://github.com/xmapst/NexusImageClean/releases/tag/1.0.1-beta)

**Comment by iarrived** [comment]
@xmapst 
Although not to print the error log, but failed to delete anything

**Comment by xmapst** [comment]
> @xmapst Although not to print the error log, but failed to delete anything

I will check again
